server:
  port:
  host: 
  network: "tcp"
  request_per_second_limit: 100

storage:
  timeout: 10s

redis:
  host: 
  port: 
  password: 
  db: 0
  pool_size: 8
  min_id_le_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  timeout: 10s

collector:
  host:
  port:
  trace_percentage: 100
  metric_interval: 1s
