server:
  port:
  host: 
  network: "tcp"
  request_per_second_limit: 100

storage:
  timeout: 10s

redis:
  host: 
  port: 
  password: 
  db: 0
  pool_size: 8
  min_id_le_conns: 5
  dial_timeout: 5s
  read_timeout: 3s
  write_timeout: 3s
  timeout: 10s

collector:
  host:
  port:
  trace_percentage: 100
  metric_interval: 1s

kafka:
  host:
  port:
  topic: "markets"
  max_attempts: 10
  write_backoff_min: 100ms
  write_backoff_max: 2s
  batch_size: 1
  batch_bytes: 1024
  get_markets_interval: 10s
  relay_interval: 3s
