
services:
  redis:
    image: redis:alpine  # Версия образа для redis
    container_name: redis_cache #Название контейнера в Docker

    ports:
      - "6379:6379" #Проброс портов из контейнера

    restart: always #Опция перезапуска

    healthcheck: #Проверка работы контейнера
      test: ["CMD","redis-cli",ping] #Команда проверки
      interval: 30s #Интервал проверки
      timeout: 5s   #Ожидание ответа
      retries: 5 #Количество попыток получить ответ от контейнера


    volumes: #Создание тома data в redis
      - redis_data:/redis

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    ports:
      - "16686:16686"
     # - "4317:4317"
     # - "4318:4318"

    restart: always
    environment:
      - DEBUG=true
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - monitoring
      
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./Config/tempo_config.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"   
    restart: always
    environment:
      - DEBUG=true
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - monitoring
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./Config/loki_config.yaml:/etc/loki/loki.yaml:ro   
      - loki_data:/loki                                    
    command: -config.file=/etc/loki/loki.yaml

    restart: always
    
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"

    volumes:
      - ./Config/prometheus_config.yaml:/etc/prometheus/prometheus.yaml:ro   
      - prometheus_data:/prprometheus
      
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.retention.time=24h'  
    
    restart: always
   
    networks:
      - monitoring


  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./Config/collector_config.yaml:/etc/otelcol/config.yaml:ro

    ports:
      - "4317:4317" 
      - "4318:4318" 

    depends_on:
      - jaeger
      - prometheus
      - loki
      - tempo
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - "3000:3000"
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
    - monitoring

volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  loki_data:
    
networks:
  monitoring:
    driver: bridge


 