
services:
  redis:
    image: redis:alpine  # Версия образа для redis
    container_name: redis_cache #Название контейнера в Docker

    ports:
      - "6379:6379" #Проброс портов из контейнера

    restart: always #Опция перезапуска

    healthcheck: #Проверка работы контейнера
      test: ["CMD","redis-cli",ping] #Команда проверки
      interval: 30s #Интервал проверки
      timeout: 5s   #Ожидание ответа
      retries: 5 #Количество попыток получить ответ от контейнера


    volumes: #Создание тома data в redis
      - redis_data:/redis

  jaeger:
    image: jaegertracing/jaeger:latest
    container_name: jaeger
    ports:
      - "16686:16686"
     # - "4317:4317"
     # - "4318:4318"

    restart: always
    environment:
      - DEBUG=true
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - monitoring
      
  tempo:
    image: grafana/tempo:latest
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./Config/tempo_config.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"   
    restart: always
    environment:
      - DEBUG=true
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - monitoring
  
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./Config/loki_config.yaml:/etc/loki/loki.yaml:ro   
      - loki_data:/loki                                    
    command: -config.file=/etc/loki/loki.yaml

    restart: always
    
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"

    volumes:
      - ./Config/prometheus_config.yaml:/etc/prometheus/prometheus.yaml:ro   
      - prometheus_data:/prprometheus
      
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.retention.time=24h'  
    
    restart: always
   
    networks:
      - monitoring


  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./Config/collector_config.yaml:/etc/otelcol/config.yaml:ro

    ports:
      - "4317:4317" 
      - "4318:4318" 

    depends_on:
      - jaeger
      - prometheus
      - loki
      - tempo
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
    - "3000:3000"
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
    - monitoring

 
  kafka:
    image: apache/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
    # KRaft обязательные настройки
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
    
    # Listener'ы (добавляем PLAINTEXT_HOST)
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
    
    # Авто-создание топиков
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    
    # Настройки по умолчанию
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    
    # Хранение данных
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    
    # Уникальный ID кластера
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    networks:
      - kafka-net
    restart: unless-stopped
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Kafka UI - веб-интерфейс
  kafka-ui:
    image: docker.redpanda.com/redpandadata/console:latest
    container_name: kafka-ui
    depends_on:
      - kafka
    ports:
      - "8085:8080"
    environment:
      KAFKA_BROKERS: kafka:9092
    networks:
      - kafka-net
    restart: unless-stopped

    
networks:
  monitoring:
    driver: bridge
  kafka-net:
    driver: bridge

volumes:
  redis_data:
    driver: local
  prometheus_data:
    driver: local
  loki_data:
    driver: local
  zookeeper_data:
    driver: local
  zookeeper_datalog:
    driver: local
  kafka_data:
    driver: local