server:
  port: 
  host: 
  network: "tcp"
  request_per_second_limit: 100
  
postgres:
  host: 
  port: 
  user: 
  password: 
  name: 
  sslmode: "disable"

jwt:
  secret:
  ttl: 2m

collector:
  host:
  port:
  trace_percentage: 100
  metric_interval: 1s