syntax = "proto3";

package order_service.v2;

import "common/common.proto";
import "google/protobuf/timestamp.proto";
import "money/money.proto";
import "validate/validate.proto";

option go_package = "github.com/DenсCPU/gRPCServices/Protobuf/gen/order_service";

service OrderService {
  /*
     The GetOrderStatus method retrieves information about a user's order.
     The request body contains the order number (order_id) and user number (user_id).
     The method returns a response with the following fields:
      -order_status,
      -order_id,
      -order coas(price),
      -number of order units (quantity),
      -the title of the market in which the order was made( market_name).
  */
  rpc GetOrderStatus(GetOrderReq) returns (GetOrderResp);

  /*
     The CreateOrder method is responsible for creating an order by the user.
     The request body contains information about:
      -user_id,
      -market_id,
      -order_type,
      -order coas(price),
      -number of order units (quantity),
      -user_role,
      -idempotency key to prevent duplicate orders.
     The method returns a response with the following fields:
      -order_id,
      -order_status.
  */
  rpc CreateOrder(CreateOrderReq) returns (CreateOrderResp);

  /*
     The StreamOrderUpdate method is responsible for receiving up-to-date information about changes in the order status.
     The request body contains information about order_id and user_id.
     The method returns a response with the following fields:
      -order_status,
      -update_status_time.
  */
  rpc StreamOrderUpdate(StreamOrderUpdateReq) returns (stream StreamOrderUpdateResp); //Получение актульного статуса заказа
}

//Request for GetOrderStatus
message GetOrderReq {
  string order_id = 1 [(validate.rules).string.uuid = true];
  string user_id = 2 [(validate.rules).string.uuid = true];
}

//Response for GetOrderStatus
message GetOrderResp {
  string order_status = 1;
  string order_id = 2;
  google.type.Money price = 3;
  int64 quantity = 4;
  string market_name = 5;
}

//Request for CreateOrder
message CreateOrderReq {
  string user_id = 1 [(validate.rules).string.uuid = true];
  string market_id = 2 [(validate.rules).string.uuid = true];
  OrderType order_type = 3;
  google.type.Money price = 4;
  int64 quantity = 5 [(validate.rules).int64.gte = 1];
  common.UserRole user_role = 6;
  string indempotency_key = 7 [(validate.rules).string.min_len = 1];
}

enum OrderType {
  ORDER_TYPE_UNSPECIFIED = 0;
  ORDER_TYPE_NORMAL = 1;
  ORDER_TYPE_EXPRESS = 2;
}

//Response for CreateOrder
message CreateOrderResp {
  string order_id = 1;
  string order_status = 2;
}

//Request for StreamOrderUpdate
message StreamOrderUpdateReq {
  string order_id = 1 [(validate.rules).string.uuid = true];
  string user_id = 2 [(validate.rules).string.uuid = true];
}

//Response for StreamOrderUpdate
message StreamOrderUpdateResp {
  string order_status = 1;
  google.protobuf.Timestamp update_status_time = 2;
}
