server:
  port: 
  host: 
  network: "tcp"
  request_per_second_limit: 100

postgres:
  host: 
  port: 
  user: 
  password: 
  name: 
  sslmode: "disable"
  chan_size: 10
  idepmpotency_cache_ttl: 5s
  market_cache_ttl: 10s

breakersetting:
  name: "OrderService"
  max_request: 5
  interval: 60s
  timeout: 10s
  max_fail_request: 10

notify:
  ticker_interval: 1ms

collector:
  host:
  port:
  trace_percentage: 100
  metric_interval: 1s

kafka:
  brokers:
  topic: "markets"
  group_id: "order-service-group"
  min_bytes: 1
  max_bytes: 1048576
  max_wait: 10s