server:
  port: 
  host: 
  network: "tcp"
  request_per_second_limit: 100

postgres:
  host: 
  port: 
  user: 
  password: 
  name: 
  sslmode: "disable"
  chan_size: 10
  idepmpotency_cache_ttl: 5s

breakersetting:
  name: "OrderService"
  max_request: 5
  interval: 60s
  timeout: 10s
  max_fail_request: 10

notify:
  ticker_interval: 1ms

collector:
  host:
  port:
  trace_percentage: 100
  metric_interval: 1s
