server:
  port: 
  host:
  write_timeout: 10s
  client_connection_timeout: 5s
  request_per_second_limit: 100 

breakersetting:
  name: "APIGetway"
  max_request: 5
  interval: 60s
  timeout: 10s
  max_fail_request: 10

collector:
  host:
  port:
  trace_percentage: 100
  metric_interval: 1s